# Generated by Django 4.1.1 on 2022-10-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_share_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_text', models.TextField()),
                ('home_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
